server:
  port: 7000

spring:
  application:
    name: orange-coupon-eureka

eureka:
  instance:
    hostname: localhost
    # 解决 Eureka Server主页进不去问题
    preferIpAddress: true
  client:
    # 表示是否从 Eureka Server 获取注册信息, 默认为true
    # 如果这是一个单节点的 Eureka Server, 则不需要同步其他节点的数据, 设置为 false
    fetch-registry: false
    # 表示是否将自己注册到 Eureka Server上, 默认为true
    # 单节点 Eureka Server将其关闭
    register-with-eureka: false
    # 设置 Eureka Server的地址, 查询服务和注册服务都需要依赖此地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/